// VideoEmbed component with standardized configuration
function VideoEmbed({ url }: { url?: string }) {
  if (!url) return null;

  // Provider-specific configurations
  // Pattern generated by Claude
  const providers = [
    {
      type: 'youtube',
      matches: (url: string) => url.includes('youtube.com') || url.includes('youtu.be'),
      getEmbedUrl: (url: string) => {
        const videoId = url.includes('v=')
          ? url.split('v=')[1].split('&')[0]
          : url.split('/').pop();
        return `https://www.youtube.com/embed/${videoId}`;
      },
      additionalProps: {
        title: 'YouTube video player',
        allow:
          'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture',
      },
    },
    {
      type: 'loom',
      matches: (url: string) => url.includes('loom.com'),
      getEmbedUrl: (url: string) => {
        // EG: https://www.loom.com/share/66a72a603b7a42ea90733fc091b73066?sid=85c180c1-feee-4c62-a723-8a27ea552683
        // could add this to remove the query param, but it should be ok as-is `?.split("?")[0]`
        const videoId = url.split('/').pop();
        return `https://www.loom.com/embed/${videoId}`;
      },
      additionalProps: {
        webkitallowfullscreen: true,
        mozallowfullscreen: true,
      },
    },
    {
      type: 'vimeo',
      matches: (url: string) => url.includes('vimeo'),
      getEmbedUrl: (url: string) => {
        const videoId = url.split('/').pop();
        return `https://player.vimeo.com/video/${videoId}`;
      },
      additionalProps: {
        allow: 'autoplay; fullscreen',
      },
    },
    // Must be last in the array
    {
      type: 'default',
      matches: () => true, // Default fallback
      getEmbedUrl: (url: string) => url,
      additionalProps: {},
    },
  ];

  // Find the first matching provider
  const provider = providers.find(provider => provider.matches(url));

  // Generate the embed URL using the provider's logic
  const embedUrl = provider?.getEmbedUrl(url);

  // Merge shared props with provider-specific props
  const iframeProps = {
    // Default Props
    width: '100%',
    height: '100%',
    frameBorder: '0',
    allowFullScreen: true,
    // Provider-specific props, if any
    ...provider?.additionalProps,
    src: embedUrl,
  };

  // Render the iframe with all props
  return <iframe {...iframeProps} />;
}

export default VideoEmbed;
